// Filter Data Constants
// Real data provided by user for Jenis Layanan (Services)

export const SERVICE_CATEGORIES = [
  { id: '01.01', name: 'Retribusi Pelayanan Kesehatan', value: '01.01', gol_id: '01' },
  { id: '01.02', name: 'Retribusi Pelayanan Tera/Tera Ulang', value: '01.02', gol_id: '01' },
  { id: '01.03', name: 'Retribusi Penggantian Biaya Cetak peta', value: '01.03', gol_id: '01' },
  { id: '01.04', name: 'Retribusi Pelayanan Pendidikan', value: '01.04', gol_id: '01' },
  { id: '01.23', name: 'Pendapatan Pelayanan Diklat', value: '01.23', gol_id: '01' },
  { id: '02.01', name: 'Retribusi KAYADA', value: '02.01', gol_id: '02' },
  { id: '02.02', name: 'Retribusi Tempat Pelelangan', value: '02.02', gol_id: '02' },
  { id: '02.03', name: 'Retribusi Tempat Penginapan/Pesanggrahan/Villa', value: '02.03', gol_id: '02' },
  { id: '02.04', name: 'Retribusi Penjualan Produk usaha Daerah', value: '02.04', gol_id: '02' },
  { id: '02.05', name: 'Retribusi Terminal', value: '02.05', gol_id: '02' },
  { id: '02.06', name: 'Retribusi Pelayanan Kepelabuhan', value: '02.06', gol_id: '02' },
  { id: '02.07', name: 'Retribusi Tempat Rekreasi dan Olahraga', value: '02.07', gol_id: '02' },
  { id: '02.16', name: 'Penyediaan tempat khusus parkir diluar badan jalan', value: '02.16', gol_id: '02' },
  { id: '02.17', name: 'Retribusi Pemanfaatan Aset Daerah', value: '02.17', gol_id: '02' },
  { id: '02.18', name: 'Retribusi Pelayanan Jasa Kepelabuhan', value: '02.18', gol_id: '02' },
  { id: '02.19', name: 'Penyediaan Tempat Kegiatan Usaha', value: '02.19', gol_id: '02' },
  { id: '02.20', name: 'Retribusi Penjualan Hasil Produksi Usaha Pemerintah Daerah', value: '02.20', gol_id: '02' },
  { id: '02.21', name: 'Retribusi Penyediaan Tempat Kegiatan Usaha berupa Pasar, Grosir, Pertokoan, dan Tempat Kegiatan Usaha Lainnya', value: '02.21', gol_id: '02' },
  { id: '02.22', name: 'Retribusi Pelayanan Tempat Rekreasi, Pariwisata, dan Olahraga', value: '02.22', gol_id: '02' },
  { id: '03.01', name: 'Retribusi Izin Trayek', value: '03.01', gol_id: '03' },
  { id: '03.02', name: 'Retribusi Izin Usaha Perikanan', value: '03.02', gol_id: '03' },
  { id: '03.03', name: 'Retribusi Perpanjangan Izin Mempekerjakan Tenaga Asing', value: '03.03', gol_id: '03' },
  { id: '03.15', name: 'Retribusi Pengelolaan Pertambangan Rakyat', value: '03.15', gol_id: '03' },
]

// Real data for Pengelola (Managers/OPD) - 36 items
export const DUMMY_MANAGERS = [
  { id: '01', name: 'DINAS PENDIDIKAN', value: '01' },
  { id: '02', name: 'DINAS KESEHATAN', value: '02' },
  { id: '03', name: 'DINAS PEKERJAAN UMUM DAN PENATAAN RUANG', value: '03' },
  { id: '04', name: 'DINAS PEKERJAAN UMUM, SUMBER DAYA AIR DAN PENATAAN RUANG', value: '04' },
  { id: '05', name: 'BADAN PENGELOLA PENDAPATAN DAERAH', value: '05' },
  { id: '06', name: 'BADAN PERENCANAAN PEMBANGUNAN DAERAH', value: '06' },
  { id: '07', name: 'DINAS PERHUBUNGAN', value: '07' },
  { id: '08', name: 'DINAS LINGKUNGAN HIDUP DAN KEHUTANAN', value: '08' },
  { id: '09', name: 'DINAS SOSIAL', value: '09' },
  { id: '10', name: 'DINAS TENAGAKERJA DAN TRANSMIGRASI', value: '10' },
  { id: '11', name: 'DINAS KOPERASI, USAHA KECIL DAN MENENGAH', value: '11' },
  { id: '12', name: 'DINAS KEPEMUDAAN DAN OLAHRAGA', value: '12' },
  { id: '13', name: 'BIRO UMUM SETDA PROV. JATENG', value: '13' },
  { id: '14', name: 'SEKRETARIAT DPRD', value: '14' },
  { id: '15', name: 'BADAN PENGHUBUNG', value: '15' },
  { id: '16', name: 'BADAN PENGEMBANGAN SUMBER DAYA MANUSIA DAERAH', value: '16' },
  { id: '17', name: 'DINAS KEARSIPAN DAN PERPUSTAKAAN', value: '17' },
  { id: '18', name: 'DINAS PERTANIAN DAN PETERNAKAN', value: '18' },
  { id: '19', name: 'DINAS PETERNAKAN DAN KESEHATAN HEWAN', value: '19' },
  { id: '20', name: 'DINAS ENERGI DAN SUMBER DAYA MINERAL', value: '20' },
  { id: '21', name: 'DINAS KELAUTAN DAN PERIKANAN', value: '21' },
  { id: '22', name: 'DINAS PERINDUSTRIAN DAN PERDAGANGAN', value: '22' },
  { id: '23', name: 'BADAN PENGELOLA KEUANGAN DAN ASET DAERAH', value: '23' },
  { id: '24', name: 'SATUAN POLISI PAMONG PRAJA', value: '24' },
  { id: '25', name: 'DINAS PENANAMAN MODAL DAN PELAYANAN TERPADU SATU PINTU', value: '25' },
  { id: '26', name: 'BADAN KEPEGAWAIAN DAERAH', value: '26' },
  { id: '27', name: 'DINAS KETAHANAN PANGAN', value: '27' },
  { id: '28', name: 'RUMAH SAKIT UMUM DAERAH Dr. MOEWARDI', value: '28' },
  { id: '29', name: 'RUMAH SAKIT UMUM DAERAH Prof. Dr. MARGONO SOEKARJO', value: '29' },
  { id: '30', name: 'RUMAH SAKIT UMUM DAERAH Dr. ADHYATMA', value: '30' },
  { id: '31', name: 'RUMAH SAKIT UMUM DAERAH dr. REHATTA', value: '31' },
  { id: '32', name: 'RUMAH SAKIT JIWA DAERAH Dr. AMINO GONDOHUTOMO', value: '32' },
  { id: '33', name: 'RUMAH SAKIT JIWA DAERAH dr. ARIF ZAINUDDIN', value: '33' },
  { id: '34', name: 'RUMAH SAKIT JIWA DAERAH Dr. RM. SOEDJARWADI', value: '34' },
  { id: '35', name: 'RUMAH SAKIT MATA SOEPARDJO RUSTAM', value: '35' },
  { id: '36', name: 'DINAS KEBUDAYAAN, PARIWISATA DAN EKONOMI KREATIF', value: '36' },
]

// Lokasi (Cities) - Real data for Jawa Tengah (35 cities)
export const DUMMY_CITIES = [
  { id: '3291', name: 'Kabupaten Banjarnegara', value: '3291' },
  { id: '3292', name: 'Kabupaten Banyumas', value: '3292' },
  { id: '3293', name: 'Kabupaten Batang', value: '3293' },
  { id: '3294', name: 'Kabupaten Blora', value: '3294' },
  { id: '3295', name: 'Kabupaten Boyolali', value: '3295' },
  { id: '3296', name: 'Kabupaten Brebes', value: '3296' },
  { id: '3297', name: 'Kabupaten Cilacap', value: '3297' },
  { id: '3298', name: 'Kabupaten Demak', value: '3298' },
  { id: '3299', name: 'Kabupaten Grobogan', value: '3299' },
  { id: '3300', name: 'Kabupaten Jepara', value: '3300' },
  { id: '3301', name: 'Kabupaten Karanganyar', value: '3301' },
  { id: '3302', name: 'Kabupaten Kebumen', value: '3302' },
  { id: '3303', name: 'Kabupaten Kendal', value: '3303' },
  { id: '3304', name: 'Kabupaten Klaten', value: '3304' },
  { id: '3305', name: 'Kabupaten Kudus', value: '3305' },
  { id: '3306', name: 'Kabupaten Magelang', value: '3306' },
  { id: '3307', name: 'Kabupaten Pati', value: '3307' },
  { id: '3308', name: 'Kabupaten Pekalongan', value: '3308' },
  { id: '3309', name: 'Kabupaten Pemalang', value: '3309' },
  { id: '3310', name: 'Kabupaten Purbalingga', value: '3310' },
  { id: '3311', name: 'Kabupaten Purworejo', value: '3311' },
  { id: '3312', name: 'Kabupaten Rembang', value: '3312' },
  { id: '3313', name: 'Kabupaten Semarang', value: '3313' },
  { id: '3314', name: 'Kabupaten Sragen', value: '3314' },
  { id: '3315', name: 'Kabupaten Sukoharjo', value: '3315' },
  { id: '3316', name: 'Kabupaten Tegal', value: '3316' },
  { id: '3317', name: 'Kabupaten Temanggung', value: '3317' },
  { id: '3318', name: 'Kabupaten Wonogiri', value: '3318' },
  { id: '3319', name: 'Kabupaten Wonosobo', value: '3319' },
  { id: '3320', name: 'Kota Magelang', value: '3320' },
  { id: '3321', name: 'Kota Pekalongan', value: '3321' },
  { id: '3322', name: 'Kota Salatiga', value: '3322' },
  { id: '3323', name: 'Kota Semarang', value: '3323' },
  { id: '3324', name: 'Kota Surakarta', value: '3324' },
  { id: '3325', name: 'Kota Tegal', value: '3325' },
]

export const DEFAULT_FILTERS = {
  city: '',
  manager: '',
  serviceType: '',
  search: ''
}

export const EMPTY_OPTIONS = {
  cities: DUMMY_CITIES,
  managers: DUMMY_MANAGERS,
  services: SERVICE_CATEGORIES
}
